config/routes.rb
Rails.application.routes.draw do
  resources :stars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' =>'posts#new', as: :new_post
  # post '/posts' => 'posts#create', as: :posts
  # get '/posts' => 'posts#index'
  # get '/posts/:id' => 'posts#show', as: :post
  # get '/posts/:id/edit' => 'posts#edit', as: :edit_post
  # patch '/posts/:id' => 'posts#update'
  # delete '/posts/:id' => 'posts#destroy'
  # get '/posts/:id/comments/new' => 'comments#new', as: :new_post_comment
  # post '/posts/:post_id/comments' => 'comments#create', as: :post_comments
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
resources :posts do
  resources :comments
  resources :favourites, only: [:create, :destroy]
  resources :stars, shallow: true, only: [:create, :update, :destroy]
end

  resources :users, only:[:create, :new, :edit, :update] do
    get :favourite_list, on: :collection
  end
  resources :sessions, only:[:new, :create, :update] do
    delete :destroy, on: :collection

end
  resources :passwords, only:[:edit,:update,:new] do
    post :link, on: :collection
    get :forgot_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :tags, only: [:index, :show]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true, uniqueness: { case_sensitive: false,
                                                 message: 'must be unique' }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :authenticate_user, except:[:index,:show]
  # this is for our post method in Ajax Blog frontend client to work
  skip_before_action :verify_authenticity_token

  def new
    @comment = Comment.new
  end

  # handles creating the comment after the form has been submitted
  def create
    @post = Post.find params[:post_id]
    comment_params = params.require(:comment).permit([:body])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.js { render :create_success }
        format.html { redirect_to post_path(@post) }
      else
        format.js { render :create_failure }
        format.html { render 'posts/show' }
      end
    end
  end

  def destroy
    # @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    respond_to do |format|
      if can? :delete, @comment
        @post = @comment.post
        @comment.destroy
        format.html { redirect_to post_path(@post), notice: 'Comment Deleted!' }
        format.js { render :destroy }
      else
        format.html { redirect_to root_path, alert: 'Access Denied. You did not create this comment!' }
        format.js { render js: 'alert("access denied");' }
       end
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class = "col-xs-12" id="<%= dom_id(c)%>">

    <div class = "col-xs-11">
     <%= c.body %>
    </div>

  <div class = "col-xs-1">
        <% if can? :delete, c  %>
          <%= link_to 'Delete', post_comment_path(@post, c),method: :delete,
                                                             remote: true,
                                                             data:{confirm: 'Are you sure you want to delete?'},
                                                             class: 'btn btn-danger btn-xs'  %>
         <% end %>
  </div>
    <hr>
</div>

app/views/comments/_form.html.erb
<div id="error_explanation">
  <%= @comment.errors.full_messages.join(', ') %>
</div>

 <%= form_for [@post, @comment], remote: true do |f| %>
 <div class = "row">
  <div class="field form-group">
     <div class = "col-md-1">
     <%= f.label :body, class: 'control-label' %>
     </div>
     <div class = "col-md-4">
      <%= f.text_area :body, class: 'form-control' %>
     </div>
  </div>
</div>

 <div class = "row">
   <div class = "col-md-2">
   </div>
    <div class="actions form-group col-md-10">
      <div class="btn btn-primary center-align">
        <%= f.submit 'Comment' %>
      </div>
    </div>
  </div>
  <% end %>

app/views/comments/create_failure.js.erb
$('#comments-form').html(' <%= j render 'form' %>');

app/views/comments/create_success.js.erb
$('#comments-loop').prepend('<%= j render 'comment', c: @comment  %>');
<% @comment = Comment.new %>
$('#comments-form').html(' <%= j render 'form' %>');

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(800, function(){
  $(this).remove();
});

app/views/comments/new.html.erb
<h2>Add a pithy comment</h2>

<%= form_for(@comment, html: {class: 'form-horizontal'}) do |p| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= p.label :title, class: 'col-sm-1 control-label' %>
    <div class="col-sm-11">
      <%= p.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="field form-group">
    <%= p.label :body, class: 'col-sm-1 control-label' %>
    <div class="col-sm-11">
      <%= p.text_area :body, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-1 col-sm-11 btn">
      <%= p.submit %>
    </div>
  </div>
<% end %>