config/routes.rb
Rails.application.routes.draw do
  resources :stars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' =>'posts#new', as: :new_post
  # post '/posts' => 'posts#create', as: :posts
  # get '/posts' => 'posts#index'
  # get '/posts/:id' => 'posts#show', as: :post
  # get '/posts/:id/edit' => 'posts#edit', as: :edit_post
  # patch '/posts/:id' => 'posts#update'
  # delete '/posts/:id' => 'posts#destroy'
  # get '/posts/:id/comments/new' => 'comments#new', as: :new_post_comment
  # post '/posts/:post_id/comments' => 'comments#create', as: :post_comments
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
resources :posts do
  resources :comments
  resources :favourites, only: [:create, :destroy]
  resources :stars, shallow: true, only: [:create, :update, :destroy]
end

  resources :users, only:[:create, :new, :edit, :update] do
    get :favourite_list, on: :collection
  end
  resources :sessions, only:[:new, :create, :update] do
    delete :destroy, on: :collection

end
  resources :passwords, only:[:edit,:update,:new] do
    post :link, on: :collection
    get :forgot_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :tags, only: [:index, :show]

end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post_id, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    @post = Post.find params[:post_id]
    @favourite = Favourite.new(user: current_user, post: @post)
    respond_to do |format|
      if cannot? :favourite, @post
        format.html { redirect_to :back, notice: '🔥Access Denied🔥' }
      elsif @favourite.save
        format.js { render :create_success }
        format.html { redirect_to :back, notice: 'Favourited!' }
      else
        format.js { render js: 'alert("Failure")' }
        format.html { redirect_to :back, alert: @favourite.errors.full_messages.join(', ') }
      end
    end
  end

  def destroy
    @favourite = Favourite.find params[:id]
    @post = @favourite.post
    respond_to do |format|
      if @favourite.destroy
        format.html { redirect_to :back, notice: 'Unfavourited!' }
        format.js { render :destroy }
      else
        format.html { redirect_to :back, alert: @favourite.errors.full_messages.join(', ') }
        format.js { render js: 'alert("access denied");' }
      end
    end
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_favourite.html.erb
<!-- <div class = "col-xs-12" id="<%= dom_id(@post)%>"> -->
  <% if user_signed_in? && can?(:favourite, @post) %>
    <% if @favourite&.persisted? %>
      <%= link_to 'Unfavourite', post_favourite_path(@post,@favourite), method: :delete, remote: true, class: 'btn btn-primary' %>
    <% else %>
      <%= link_to 'Favourite', post_favourites_path(@post), method: :post, remote: true, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<!-- </div> -->
(<%= pluralize @post.favourites.count, "favourite" %>)

app/views/favourites/create_success.js.erb
$('#<%= dom_id @post %> .favourite-button').html('<%= j render('favourite', post: @post) %>')

app/views/favourites/destroy.js.erb
$('#<%= dom_id @post %> .favourite-button').html('<%= j render('favourite', post: @post) %>')