config/routes.rb
Rails.application.routes.draw do
  resources :stars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' =>'posts#new', as: :new_post
  # post '/posts' => 'posts#create', as: :posts
  # get '/posts' => 'posts#index'
  # get '/posts/:id' => 'posts#show', as: :post
  # get '/posts/:id/edit' => 'posts#edit', as: :edit_post
  # patch '/posts/:id' => 'posts#update'
  # delete '/posts/:id' => 'posts#destroy'
  # get '/posts/:id/comments/new' => 'comments#new', as: :new_post_comment
  # post '/posts/:post_id/comments' => 'comments#create', as: :post_comments
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
resources :posts do
  resources :comments
  resources :favourites, only: [:create, :destroy]
  resources :stars, shallow: true, only: [:create, :update, :destroy]
end

  resources :users, only:[:create, :new, :edit, :update] do
    get :favourite_list, on: :collection
  end
  resources :sessions, only:[:new, :create, :update] do
    delete :destroy, on: :collection

end
  resources :passwords, only:[:edit,:update,:new] do
    post :link, on: :collection
    get :forgot_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :tags, only: [:index, :show]

end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user

  has_many :stars, dependent: :destroy
  has_many :star_raters, dependent: :destroy

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :category
  belongs_to :user
  validates :title, presence: true, length: { minimum: 7 }
  # uniqueness:{case_sensitive:false,
  #                                                 message: "must be unique"}

  validates :body, presence: true

  # after_initialize :body_snippet
  # Test drive a method `body_snippet`  that returns a maximum of a
  # 100 characters with "..." of the body if it's more than a 100 characters long.

  def user_full_name
    if user
      user.first_name + ' ' + user.last_name
    else
      'Anonymous'
    end
  end

  def body_snippet
    body_length = body.length
    body.slice(0, 100) + '...' if body_length > 100
  end

  def favourite_for(user)
    # favourites.find_by(user: user)
    favourites.find_by_user_id(user)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_access, only: [:edit, :update, :destroy]

  # ACTIONS
  # creates new post, displays a form
  def new
    @post = Post.new
    @category = Category.all
    @comments = Comment.all
  end

  # handles creating the post after the form has been submitted
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  # shows particular posts when you click on them
  def show
    # find_post method gets called here
    @comment = Comment.new
    @favourite = @post.favourite_for(current_user)
    respond_to do |format|
      format.html { render }
      format.text { render }
      format.xml  { render xml: @post }
      format.json { render json: @post.to_json(include: :comments) }
    end
  end

  # displays all the posts
  def index
    @posts = Post.order(created_at: :desc)
    respond_to do |format|
      format.html { render }
      format.text { render }
      format.xml  { render xml: @posts }
      format.json { render json: @posts.to_json }
    end
  end

  # gets a post for editing
  def edit
    # find_post method gets called here
  end

  def update
    # find_post method gets called here
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    # find_post method gets called here
    @post.destroy
    redirect_to posts_path
  end

  # Methods created to refactor code

  private

  # find_post method, gets called on :show, :edit, :update, :destroy
  def find_post
    @post = Post.find params[:id]
  end

  private

  # post_params method used for defining params in create and update
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :comment_id, tag_ids: [])
  end

  def authorize_access
    unless can? :manage, @post
      # head :unauthorized #this will send empty HTTP request
      redirect_to root_path, alert: 'Access Denied. You did not create this question!'
     end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class = "container-fluid">

  <h3> Create a New Comment</h3>
   <!-- comments form was here  -->
   <div id = "comments-form">
     <%= render '/comments/form' %>
 </div>

<!-- shows comments -->
    <% if @post.comments.size != 0 %>
  <h3>Comments</h3>
      <div class = "row">
        <div class = "col-md-12">
          <div id = "comments-loop">
              <% @post.comments.each do |c| %>
              <div id="<%= dom_id(c)%>">
              <!-- comments loop was here  -->
              <%= render '/comments/comment', {c: c} %>
              <% end %>
         </div>
      </div>
   </div>
 </div>
   <% end %>
  </div>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {class: 'form-horizontal'}) do |p| %>
   <% if @post.errors.any? %>
  <div id="error_explanation">
<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
   <% end %>
    </ul>
  </div>
<% end %>

  <div class="field form-group">
    <%= p.label :title, class: 'col-sm-1 control-label' %>
    <div class="col-sm-11">
    <%= p.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class = "field form-group">
  <%= p.label :category_id, class: 'col-sm-1 dropdown-label'%>
    <div class = "col-sm-11">
  <%= p.collection_select :category_id, @category, :id, :title %>
    </div>
  </div>

  <div class="field form-group">
    <%= p.label :body, class: 'col-sm-1 control-label' %>
    <div class="col-sm-11">
      <%= p.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group" >
    <%= p.collection_select(
     :tag_ids, Tag.all, :id, :name, {},
     {multiple: true, class: 'chosen-select'}
    ) %>
    <div class="col-sm-11">
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-1 col-sm-11 btn">
      <%= p.submit %>
    </div>
  </div>
<% end %>

<script>
  $('.chosen-select').chosen({ width: '300px'})
</script>

app/views/posts/_post.html.erb
<!-- Post partial, everything related to my post -->
<div class ="container-fluid">
<div id="<%= dom_id(@post) %>">
    <div class = "row">
      <div class = "col-md-12">
        <h2><%= @post.title %></h2>
      </div>
    </div>

    <div class = "row">
      <div class = "col-md-12">
        <h4><%= @post.category.title %></h4>
      </div>
    </div>

    <div class = "row">
      <div class = "col-md-2">
       <p>By: &nbsp<%= @post.user_full_name %></p>
      </div>
      <div class = "col-md-10">
        <%= @post.created_at.strftime("%d %b %Y") %>
      </div>
    </div>

    <div class = "row">
      <div class = "col-md-12">
        <section class = "star-widget">
          Rating: <%= average_star(@post) %>
        </section>
     </div>
    </div>

    <div class = "row">
      <div class = "col-md-12 post-body">
        <%= @post.body %>
      </div>
    </div>


    <div class = "row">
      <div class = "col-md-12">
      <% if can? :manage, @post  %>
        <%= link_to 'Edit', edit_post_path(@post),class: 'btn btn-primary' %>
        <%= link_to 'Delete', post_path(@post), method: :delete,
                                              data:{confirm: 'Are you sure you want to delete?'},class: 'btn btn-danger'  %>
      <% end %>

   <!-- favourites were here  -->
   <div class= "favourite-button">
     <%= render '/favourites/favourite', post: @post %>
   </div>

    
     </div>
    </div>
</div>

  <div class = "row">
  <div class = 'chosen-select col-md-12'>
    <button class = "tag-widget btn btn-default">
       Tags: <%= @post.tags.map(&:name).join(", ") %>
    </button>
  </div>
  </div>

  <div class = "row">
    <section class = "star-widget col-md-12">
      Rate this post: <%= display_star(@post) %>
    </section>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>

 <%= render 'form' %>

app/views/posts/index.html.erb
<div class = "container-fluid">

  <div class = "row">
    <div class = "col-md-12">
     <h1>Posts</h1>
    </div>
  </div>

  <div class = "posts row">
    <div class = "col-md-12">
      <% @posts.each do |p| %>
      <%= link_to p.title, post_path(p) %>
     <hr>
      <% end %>
    </div>
  </div>

  <div class = "row">
    <div class = "col-md-12">
     <button class = "btn btn-primary"> <%= link_to 'Show by Tag', tags_path  %></button>
   </div>
 </div>


</div>

app/views/posts/new.html.erb
<h1>Create a new post </h1>
   <%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post' %>

<%= render 'comment' %>