config/routes.rb
Rails.application.routes.draw do
  resources :stars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'home#index', as: :home
  get '/about' => 'home#about'
  # get '/posts/new' =>'posts#new', as: :new_post
  # post '/posts' => 'posts#create', as: :posts
  # get '/posts' => 'posts#index'
  # get '/posts/:id' => 'posts#show', as: :post
  # get '/posts/:id/edit' => 'posts#edit', as: :edit_post
  # patch '/posts/:id' => 'posts#update'
  # delete '/posts/:id' => 'posts#destroy'
  # get '/posts/:id/comments/new' => 'comments#new', as: :new_post_comment
  # post '/posts/:post_id/comments' => 'comments#create', as: :post_comments
  # delete 'posts/:post_id/comments/:id' => 'comments#destroy'
resources :posts do
  resources :comments
  resources :favourites, only: [:create, :destroy]
  resources :stars, shallow: true, only: [:create, :update, :destroy]
end

  resources :users, only:[:create, :new, :edit, :update] do
    get :favourite_list, on: :collection
  end
  resources :sessions, only:[:new, :create, :update] do
    delete :destroy, on: :collection

end
  resources :passwords, only:[:edit,:update,:new] do
    post :link, on: :collection
    get :forgot_password, on: :collection
    patch :update_password, on: :collection
  end

  resources :tags, only: [:index, :show]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    cannot :favourite, Post do |p|
      p.user == user
    end

    can :favourite, Post do |p|
      user != p.user
    end

    can :manage, Post do |p|
      p.user == user
    end

    can :delete, Comment do |c|
      c.user == user || c.post.user == user
    end

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def error_description
    errors.full_messages.join(', ')
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body, presence: true, uniqueness: { case_sensitive: false,
                                                 message: 'must be unique' }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence:true,
  validates :name, presence:true,
  validates :subject, presence:true,
  validates :message, presence:true,
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :post_id, uniqueness: { scope: :user_id }
  validates :user_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user

  has_many :stars, dependent: :destroy
  has_many :star_raters, dependent: :destroy

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :category
  belongs_to :user
  validates :title, presence: true, length: { minimum: 7 }
  # uniqueness:{case_sensitive:false,
  #                                                 message: "must be unique"}

  validates :body, presence: true

  # after_initialize :body_snippet
  # Test drive a method `body_snippet`  that returns a maximum of a
  # 100 characters with "..." of the body if it's more than a 100 characters long.

  def user_full_name
    if user
      user.first_name + ' ' + user.last_name
    else
      'Anonymous'
    end
  end

  def body_snippet
    body_length = body.length
    body.slice(0, 100) + '...' if body_length > 100
  end

  def favourite_for(user)
    # favourites.find_by(user: user)
    favourites.find_by_user_id(user)
  end
  
end

app/models/star.rb
class Star < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
  validates :post_id, presence: true
  # validates :star_count, numericality: {less_than_or_equal_to: 5, greater_than_or_equal_to: 0}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post

  validates :tag_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :favourites, dependent: :destroy
  has_many :favourited_posts, through: :favourites, source: :post

  has_many :stars, dependent: :destroy
  has_many :starred_posts, through: :stars, source: :post

  has_secure_password

  before_validation :downcase_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: VALID_EMAIL_REGEX

  private

  def downcase_email
    email.downcase! if email.present?
  end

  def full_name
    "#{first_name} #{last_name}".strip.squeeze(' ').titleize
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar  animated navbar-fixed-top navbar-mobile navbar-inverse" role="navigation">
    <div class="navbar-header">
        <a class="entypo-book-open navbar-brand animated" href="/?lang=en"></a>
    </div>
    <div class="navbar-collapse collapse">
        <ul id="main-nav" class="nav navbar-nav">

            <li><%= link_to 'HOME', home_path %><span class="line"></span></a></li>

            <li><%= link_to 'ALL POSTS', posts_path %><span class="line"></span></a></li>

            <li><%= link_to 'NEW POST', new_post_path %><span class="line"></span></a></li>

            <% if user_signed_in? %>
              <li><%= link_to 'FAVOURITES', favourite_list_users_path %><span class="line"></span></a></li>
              <li><%= link_to 'UPDATE PASSWORD', edit_password_path(current_user)%><span class="line"></span></a></li>
              <li><%= link_to 'SIGN OUT', sessions_path, method: :delete %><span class="line"></span></a></li>
              <li><%= link_to 'PROFILE', edit_user_path(current_user)%><span class="line"></span></a></li>
            <% else %>
              <li><%= link_to 'SIGN UP', new_user_path %><span class="line"></span></a></li>
              <li><%= link_to 'SIGN IN', new_session_path %><span class="line"></span></a></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class = "container-fluid">
      <%= flash[:notice] || flash[:alert] %>

         <%= csrf_meta_tag %>
          <%= yield %>
   </div>
  </body>
</html>